//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goods()
        {
            this.OrderGoods = new HashSet<OrderGoods>();
            this.ShoppingCar = new HashSet<ShoppingCar>();
        }
    
        public int GoodsID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string GoodsName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public string Details { get; set; }
        public string GoodsPic { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    
        public virtual GoodsCategory GoodsCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderGoods> OrderGoods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCar> ShoppingCar { get; set; }
    }
}
